### ISSUE TITLE
Getting repository not found error

### ISSUE THREAD

**Issue by arminmor** [giovannirossini/aws-eks#2]
Hi, 

I tried to use your action in my workflow as follows:

```
      - name: Test
        uses: giovannirossini/aws-eks-kubectl-action@v1
        with:
          cluster-name: mycluster
          command: |
            kubectl get nodes
```

But I got the following error:

`Error: Unable to resolve action giovannirossini/aws-eks-kubectl-action, repository not found`
